server:
  port: 5000
winefox:
  app:
    version: @project.version@
    update:
      github-token: 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
      # 你的GitHub仓库，格式: "owner/repo" (!!重要：请修改为你自己的仓库!!)
      github-repo: "FlanChanXwO/winefox-bot"
      # 当前运行的JAR文件名，用于更新替换 (!!重要：名称必须与打包后的jar文件名一致!!)
      # 你可以在 pom.xml 的 <build><finalName>...</finalName></build> 标签中固定它
      # 例如： <finalName>winefox-bot</finalName> 打包后就是 winefox-bot.jar
      current-jar-name: "winefox-bot.jar"
      # GitHub API 地址，通常不需要修改
      github-api-url: "https://api.github.com/repos/{repo}/releases/tags/{tag}"
      # Release 的标签名，与 GitHub Actions 工作流中的 'tag_name' 保持一致
      release-tag: "latest"