spring:
  thymeleaf:
    # 【生产环境】指向 JAR 包外部的 resources/templates 目录
    prefix: file:./resources/templates/
    cache: false

  web:
    resources:
      # 【生产环境】指向 JAR 包外部的 resources/static 目录
      static-locations: file:./resources/static/, classpath:/META-INF/resources/